name: Aylus 4 hours before
on:
  schedule:
    - cron: '0 7 * * 0'  # Every Sunday at 07:00 UTC will notify the TC with 4 hours head-of-time   [min-hour-day_of_month-month-day_of_week]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.TC_DC_WH }}
        shell: bash
        run: |
          # # # Get the next Friday's date (including today if it's Friday)
          # # NEXT_TIME=$(date -u -d "next Fri" +%Y-%m-%d)

          # Get Todays date (Sunday)
          NEXT_TIME=$(date -u +%Y-%m-%d)

          # Set TC time at 09:00 UTC+0 on that Friday
          MEETING_TIME_UTC="${NEXT_TIME} 11:00:00"

          # Convert to Unix timestamp
          TIMESTAMP=$(date -d "$MEETING_TIME_UTC" +%s)

          # Create message
          MESSAGE="**Aylus TC** soon <t:${TIMESTAMP}> <t:${TIMESTAMP}:R>. prepare to send ships on time. @everyone"

          # Use jq to build JSON payload safely
          PAYLOAD=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')

          # Send to Discord
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK"
